server:
  port: 8055
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost:27017/sec?authSource=admin
#      uri: mongodb://localhost:27017/blog
      auto-index-creation: true

jwt:
  secretKey: ecf1222c-88fd-47f3-988f-bdd78bade1ad
logging:
  level:
    com.example: DEBUG
    org.springframework.web: DEBUG

